apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web
  labels:
    app: my-web-app
spec:
  selector:
    matchLabels:
      project: webapp
  template:
    metadata:
      labels:
        project: webapp
    spec:
      containers:
        - name: apache-app
          image: fourtynight/k8sphp:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-on-my-pod
  labels:
    app: my-web-app
spec:
  selector:
    project: webapp
  ports:
    - name       : app-listener
      protocol   : TCP
      port       : 80
      targetPort : 80
  type: LoadBalancer